import Head from 'next/head';
import Header from '../containers/Header';
import Hero from '../containers/Hero';
import Zx9SpeakerCard from '../containers/Zx9SpeakerCard';
import Zx7SpeakerCard from '../containers/Zx7SpeakerCard';
import Yx1EarphonesCard from '../containers/Yx1EarphonesCard';
import CategorySelection from '../containers/CategorySelection';
import BestEquipment from '../containers/BestEquipment';
import Footer from '../containers/Footer';

export default function Home() {
	return (
		<div className=''>
			<Head>
				<title>Audiophile</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.png' />
			</Head>
			<Header />
			<Hero />
			<CategorySelection />
			<div className='p-6'>
				<Zx9SpeakerCard />
				<Zx7SpeakerCard />
				<Yx1EarphonesCard />
			</div>
			<BestEquipment />
			<Footer />
		</div>
	);
}
